In [1]:
# Data science in Microsoft Fabric

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 3, Finished, Available, Finished)

In [2]:
# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "mlsamples"
blob_relative_path = "diabetes"
blob_sas_token = r"" # Blank since container is Anonymous access
    
# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)
    
# Spark read parquet, note that it won't load any data yet by now
df = spark.read.parquet(wasbs_path)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 4, Finished, Available, Finished)

Remote blob path: wasbs://mlsamples@azureopendatastorage.blob.core.windows.net/diabetes

In [3]:
display(df)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 5, Finished, Available, Finished)

SynapseWidget(Synapse.DataFrame, 5348a6d8-e3c7-4d27-ba93-37f5e7876aeb)

In [4]:
df = df.toPandas()
df.head()

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 6, Finished, Available, Finished)

   AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y
0   59    2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151
1   48    1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75
2   72    2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141
3   24    1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206
4   50    1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135

In [5]:
# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Created column 'Risk' from formula
    df['Risk'] = (df['Y'] > 211.5).astype(int)
    return df

df_clean = clean_data(df.copy())
df_clean.head()

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 20, Finished, Available, Finished)

   AGE  SEX   BMI     BP   S1     S2    S3   S4      S5  S6    Y  Risk
0   59    2  32.1  101.0  157   93.2  38.0  4.0  4.8598  87  151     0
1   48    1  21.6   87.0  183  103.2  70.0  3.0  3.8918  69   75     0
2   72    2  30.5   93.0  156   93.6  41.0  4.0  4.6728  85  141     0
3   24    1  25.3   84.0  198  131.4  40.0  5.0  4.8903  89  206     0
4   50    1  23.0  101.0  192  125.4  52.0  4.0  4.2905  80  135     0

In [6]:
from sklearn.model_selection import train_test_split
    
X, y = df_clean[['AGE','SEX','BMI','BP','S1','S2','S3','S4','S5','S6']].values, df_clean['Y'].values
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 21, Finished, Available, Finished)

In [7]:
import mlflow
experiment_name = "diabetes-regression"
mlflow.set_experiment(experiment_name)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 22, Finished, Available, Finished)

2025/03/05 09:18:45 INFO mlflow.tracking.fluent: Experiment with name 'diabetes-regression' does not exist. Creating a new experiment.

In [8]:
from sklearn.linear_model import LinearRegression
    
with mlflow.start_run():
   mlflow.autolog()
    
   model = LinearRegression()
   model.fit(X_train, y_train)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 23, Finished, Available, Finished)

2025/03/05 09:18:55 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
2025/03/05 09:19:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/trusted-service-user/cluster-env/trident_env/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."

In [9]:
from sklearn.model_selection import train_test_split
    
X, y = df_clean[['AGE','SEX','BMI','BP','S1','S2','S3','S4','S5','S6']].values, df_clean['Risk'].values
    
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 24, Finished, Available, Finished)

In [10]:
import mlflow
experiment_name = "diabetes-classification"
mlflow.set_experiment(experiment_name)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 25, Finished, Available, Finished)

2025/03/05 09:19:15 INFO mlflow.tracking.fluent: Experiment with name 'diabetes-classification' does not exist. Creating a new experiment.

In [11]:
from sklearn.linear_model import LogisticRegression
    
with mlflow.start_run():
    mlflow.sklearn.autolog()

    model = LogisticRegression(C=1/0.1, solver="liblinear").fit(X_train, y_train)

StatementMeta(, 3fcd002a-aac8-4e53-9c00-1c1a488bb263, 26, Finished, Available, Finished)